# Generated by Django 4.1.4 on 2023-04-14 06:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='lend_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='leave',
            name='lstart_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
