# Generated by Django 4.1.4 on 2023-04-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_leave_lend_date_alter_leave_lstart_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='lend_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leave',
            name='lstart_date',
            field=models.DateField(),
        ),
    ]
