# Generated by Django 4.1.4 on 2023-04-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('adate', models.DateField()),
                ('atime', models.TimeField()),
                ('aduration', models.DurationField()),
                ('aprice', models.IntegerField(default=10)),
                ('mobile_no', models.CharField(max_length=13)),
                ('astatus', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCEL', 'Cancel'), ('NOSHOW', 'NoShow')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('hid', models.AutoField(primary_key=True, serialize=False)),
                ('hdesc', models.CharField(max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=50)),
                ('sprice', models.IntegerField(default=0)),
                ('sdesc', models.CharField(default='', max_length=500)),
                ('simg', models.ImageField(default='', upload_to='service/images')),
            ],
        ),
    ]
