# Generated by Django 4.1.4 on 2023-04-13 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0001_initial'),
        ('appointment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('rname', models.CharField(max_length=50)),
                ('contactno', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=700)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=60)),
                ('locality', models.CharField(default='', max_length=50)),
                ('postcode', models.CharField(max_length=6)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('order_place_date', models.DateField()),
                ('payment_mode', models.CharField(default='COD', max_length=50)),
                ('payment_date', models.DateField()),
                ('total_amount', models.FloatField()),
                ('transaction_id', models.CharField(max_length=50)),
                ('delivered_status', models.CharField(choices=[('YES', 'Delivered'), ('NO', 'Not Deliverd')], max_length=10)),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.address')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=50)),
                ('pprice', models.IntegerField(default=0)),
                ('pdesc', models.CharField(default='', max_length=500)),
                ('pinfo', models.CharField(default='', max_length=700)),
                ('pstock', models.IntegerField(default=0)),
                ('pimg', models.ImageField(blank=True, null=True, upload_to='shop/images')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_d_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.FloatField(default=1)),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('fdesc', models.CharField(max_length=500)),
                ('fdate', models.DateField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('sid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.service')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
