# Generated by Django 4.2 on 2023-04-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_feedback_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pdesc',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='pinfo',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
